sudo: required
dist: trusty
addons:
  artifacts:
    paths:
      - results
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
language: node_js
node_js:
  - '7'
cache:
  directories:
    - node_modules
    - bower_components
    - $HOME/.npm
    - $HOME/.cache
before_script:
  - npm install
before_deploy:
  - npm run build
env:
  global:
    - NODE_ENV=testing
    - ARTIFACTS_BUCKET=js-tasks-ru
    - secure: >-
        BjGwBAFq6VaTWdvMEGvwLmuERQ+whyGntWK18IGtECQSAx+xU9Db23sDEW8CallAETBSAzZGAMY1+oS9d4X0L1CnMH2g7Hhb9jQ3zfUWlM87+yDCuKxUjjbxlCQXHkg0gCaFSKk0H8l1DSrZPrDuWwFRVPJ/0PZBoRR74JexvJWcKjrpdi5zvbJkwgNaTZZG9/HZNlz5zudwhrdcbUdeREzViydftB47tCwH86jKW8+/GRkfQY6ndA1s7g81cSmu6rY4IoXbSw0mfj2cKJ5g2biX2a+08PeVqjt5wwCAbPXvp7Pn8rC+gloakunFZg6wEAb0otJgydl9BAuMKxvveQNx5Gp+w0XdwRd6N9h46+lqkW+ik7AE1zBHmY5ZL4sZSi3Rdbzp0SNTCRgSCNkcG3ps4T7dVSR/KlFD31tR2SuRu9dC3i77dzkytnbQk6wnTFF2ruA4ZrQMS2f1HNy2nOY+4+RyzdAKr0EBznsXvgrHoH5cCzC0479Yjbh2GdEuwjX0FKM77USjwFN0klnZ82ZnG4AoMeRWGgPt51eix2jE39t5x7XOQQd/4lQiyUjNHt5OGVCBlWJLrnsn5oPMES/w9ltn8gDLlmcfcEGVqh9oJWb4zlfxm8oQ9aC/wtHfqNyVnxTTJzl6lt/H6uNZPF1rjLzerSLevuvWs4Kzj/I=
    - secure: >-
        ZCGm4AjelUo2EOg7rD3zJ2JbUzZxxgnGEqrdeGL6mp8/rH2Aox3ku2wYDBT8u7ydk6YpzGNGyza+7i4wjuHab4f/PgF6cJ8zmu9dAfpI8Q9TSxJ6fNfQ7mTSx+SC4FcC329KyoVXhiBgroekcHH4QAqDn2pi5uei5xkPITiw8jJqlYfrI2NAydS+3WqTQJTt0kAN+bNic1hoI/tnl0UaKH+1PLRPUGA2SS1v7HBYSdryaqD2OmipMhVrmkrGzbh4qqfEafBw81tNCrFHR87rDzrENnWxe4qgSWBSMKBLvenzip2QW3r4BeOrVEt3CMYYIxdzDQVYth6A5AmpAkYbcVyoV3h/cw3fBZl9bYN3vAmDdD4nB7r6qQ3yx8/yR+X74PBIlgcmRyGL4M4BkRUGBR2GMez1M5eDi41uZYmiHleo8KpMWWAX1WNTCdf4vM3GDw2dA88yqYAOmbcFbbl2pt46u6tKVDKGYFwAk5vxzqlcRCWp3PrCTJEBv1XWUJyyOkO9M4kTw8hVOWu9gD7H4rB4/E7JpxMmRfDXupEkeXNHyfjZpCMgIb1K1KNevDP0WzPFziIZ1rLM/+0jMNZqhT2wI2i3gJKC2wWkhs4oRKvO0GIhtprH8j7RyU1CqWmKLmr96YxnW47C7CyRkrdblPECUxMWRZbJPgzE3930yKg=
script:
  - npm run test
notifications:
  webhooks: 'http://learn.javascript.ru/automation/ci/build'
